# -*- coding: utf-8; compile-command: "scp cable.yml s:/var/www/shogi_web_production/current/config" -*-
development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: shogi_web_development

test:
  adapter: test

production:
  # adapter: async
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/2" } %>
  channel_prefix: shogi_web_production
