---
# このファイルはバックグランド側しか読まない

# スレッド数
:concurrency: 2

:verbose: false
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq_development.log

staging:
  :concurrency: 1
  :logfile: log/sidekiq_staging.log

production:
  :concurrency: 5
  :logfile: log/sidekiq_production.log

:queues:
  - most_high
  - high
  - default
  - low
  - batch
  - most_low
